### ISSUE TITLE
frontend can't resolve localhost when using docker-compose default network

### ISSUE THREAD

**Issue by rafaeltuelho** [Hyperfoil/vehicle-market#1]
When running on Docker on Mac (x86) the frontend app can't connect to the backend microservices using localhost addr.
You need to pass the services' names using env vars in the `scripts/docker-compose.yaml`

**Comment by rvansa** [comment]
Hi @stalep, could you figure out an assignee for this repo?

**Comment by stalep** [comment]
So you're saying you're too good for us now!!??? :)
We'll ofc fix it, I hope you're good!
